project:
  type: website

website:
  title: "Yashvardhan Jain"
  navbar:
    right:
      - blog.qmd
      - icon: substack
      - text: Subtle Digressions Newsletter
        href: https://www.subtledigressions.com
      
format:
  html:
    theme:
      - sketchy
      - dark
      - brand
    css: styles.css
