project:
  type: website

website:
  title: "Yashvardhan Jain"
  navbar:
    right:
      - blog.qmd
      - icon: substack
      - text: Substack
        href: https://www.subtledigressions.com
      - icon: github
        href: https://github.com/J-yash
      
format:
  html:
    theme:
      - sketchy
      - dark
      - brand
    css: styles.css
